In [2]:
import tensorflow as tf
import numpy as np

In [11]:
tf.reset_default_graph()

a = tf.constant(1, name='a')
b = tf.constant(2, name='b')
c = a+b

with tf.Session() as sess:
    tf.summary.FileWriter('logs', graph = sess.graph)
    _c = sess.run(c)

In [12]:
c

<tf.Tensor 'add:0' shape=() dtype=int32>

In [13]:
_c

3

In [ ]:
# EX 2

In [11]:
tf.reset_default_graph()

x = tf.placeholder(tf.float32, name='x')
y = tf.placeholder(tf.float32, name='y')
z = x+y

with tf.Session() as sess:
    _z = sess.run(z, feed_dict={x:3, y:2})
    print(_z)
    _z = sess.run(z, feed_dict={x:13, y:2})
    print(_z)
    

5.0
15.0


In [12]:
# EX 3

In [14]:
x_np = np.array([[1,2], [3,4]], dtype = np.float32)
y_np = np.array([[1],[2]], dtype = np.float32)

In [21]:
np.dot(x_np, y_np)

array([[ 5.],
       [11.]], dtype=float32)

In [23]:
tf.reset_default_graph()

x = tf.placeholder(tf.float32,[2,2], name='x')
y = tf.placeholder(tf.float32,[2,1], name='y')
z = tf.matmul(x,y)

with tf.Session() as sess:
    _z = sess.run(z, feed_dict={x:x_np, y:y_np})
    print(_z)

    

[[ 5.]
 [11.]]


In [ ]:
#EX 4

In [41]:
tf.reset_default_graph()

x = tf.Variable(x_np, dtype=tf.float32,name='x')
y = tf.Variable(y_np, dtype=tf.float32,name='y')
z = tf.matmul(x,y)
w = tf.add(z,x)

with tf.Session() as sess:
    tf.summary.FileWriter('logs', graph = sess.graph)
    sess.run(tf.global_variables_initializer())
    _z = sess.run(z)
    _w = sess.run(w)
    print(_w)
    print(_z)
    print(z.eval())
    print(tf.get_default_session().run(z))


[[ 6.  7.]
 [14. 15.]]
[[ 5.]
 [11.]]
[[ 5.]
 [11.]]
[[ 5.]
 [11.]]


In [38]:
z

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=float32>

In [39]:
x

<tf.Variable 'x:0' shape=(2, 2) dtype=float32_ref>