In [1]:
import numpy as np
import tensorflow as tf

In [2]:
filter_np = np.arange(1,10).reshape(3,3,1,1).astype(np.float32)
input_np = np.arange(1,17).reshape(1,4,4,1).astype('float32')

Conv2D

In [31]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.conv2d(input, filter, [1,1,1,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)


_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[111. 178. 217. 145.]
 [231. 348. 393. 252.]
 [363. 528. 573. 360.]
 [197. 274. 295. 175.]]


In [16]:
assert 111 == 5*1+6*2+8*5+9*6

In [17]:
assert 573 == 6*1 + 7*2 + 8*3 + 10*4 + 11*5+ 12*6 + 14*7+ 15*8 + 16*9

In [30]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.conv2d(input, filter, [1,1,1,1], 'VALID')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

    
print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)


_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[348. 393.]
 [528. 573.]]


In [29]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.conv2d(input, filter, [1,2,1,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[231. 348. 393. 252.]
 [197. 274. 295. 175.]]


## Conv2d vs Transposed_conv2d

In [28]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.conv2d_transpose(input, filter, [1,4,4,1],[1,1,1,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

    
print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[ 29.  62.  83.  75.]
 [ 99. 192. 237. 198.]
 [207. 372. 417. 330.]
 [263. 446. 485. 365.]]


In [34]:
assert 29 == 1*5 + 2*4 + 5*2 + 6*1

In [35]:
assert 365 == 11*9 + 12*8 + 15*6 + 16*5

In [38]:
tf.reset_default_graph()
filter = tf.Variable(filter_np[::-1,::-1,:,:])
input = tf.Variable(input_np)
output = tf.nn.conv2d(input, filter,[1,1,1,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

    
print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]
_output
 [[ 29.  62.  83.  75.]
 [ 99. 192. 237. 198.]
 [207. 372. 417. 330.]
 [263. 446. 485. 365.]]


In [32]:
trans_filter_np = filter_np[::-1,::-1,:,:]

In [33]:
print(np.squeeze(trans_filter_np))

[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [50]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.conv2d_transpose(input, filter, [1,16,16,1],[1,4,4,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

    
print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[  1.   2.   3.   0.   2.   4.   6.   0.   3.   6.   9.   0.   4.   8.
   12.   0.]
 [  4.   5.   6.   0.   8.  10.  12.   0.  12.  15.  18.   0.  16.  20.
   24.   0.]
 [  7.   8.   9.   0.  14.  16.  18.   0.  21.  24.  27.   0.  28.  32.
   36.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  5.  10.  15.   0.   6.  12.  18.   0.   7.  14.  21.   0.   8.  16.
   24.   0.]
 [ 20.  25.  30.   0.  24.  30.  36.   0.  28.  35.  42.   0.  32.  40.
   48.   0.]
 [ 35.  40.  45.   0.  42.  48.  54.   0.  49.  56.  63.   0.  56.  64.
   72.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  9.  18.  27.   0.  10.  20.  30.   0.  11.  22.  33.   0.  12.  24.
   36.   0.]
 [ 36.  45.  54.   0.  40.  50.  60.   0.  44.  55.  66.   0.  48.  60.
   72.   0.]
 [ 63.  72

In [51]:
tf.reset_default_graph()
unsampled_input = np.zeros(shape=[1,16,16,1]).astype(np.float32)
unsampled_input[:,1::4,1::4,:] = input_np
filter = tf.Variable(filter_np[::-1,::-1,:,:])
input = tf.Variable(unsampled_input)
output = tf.nn.conv2d(unsampled_input, filter,[1,1,1,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

    
print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.  6.  0.  0.  0.  7.  0.  0.  0.  8.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  9.  0.  0.  0. 10.  0.  0.  0. 11.  0.  0.  0. 12.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 13.  0.  0.  0. 14.  0.  0.  0. 15.  0.  0.  0. 16.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 