In [1]:
import numpy as np
import tensorflow as tf

In [2]:
filter_np = np.arange(1,10).reshape(3,3,1,1).astype(np.float32)
input_np = np.arange(1,17).reshape(1,4,4,1).astype('float32')

In [3]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.conv2d(input, filter, [1,1,1,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)


Instructions for updating:
Colocations handled automatically by placer.
_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[111. 178. 217. 145.]
 [231. 348. 393. 252.]
 [363. 528. 573. 360.]
 [197. 274. 295. 175.]]


In [6]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.atrous_conv2d(input, filter, 2, 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)


_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[194. 222. 170. 194.]
 [306. 334. 266. 290.]
 [122. 138.  98. 110.]
 [186. 202. 146. 158.]]


In [12]:
tf.reset_default_graph()
new_filter = np.zeros([5,5,1,1,]).astype(np.float32)
new_filter[0::2,0::2,:,:] = filter_np


filter = tf.Variable(new_filter)
input = tf.Variable(input_np)
output = tf.nn.atrous_conv2d(input, filter, 2, 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)



_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 0. 2. 0. 3.]
 [0. 0. 0. 0. 0.]
 [4. 0. 5. 0. 6.]
 [0. 0. 0. 0. 0.]
 [7. 0. 8. 0. 9.]]
_output
 [[ 5. 10. 15. 20.]
 [25. 30. 35. 40.]
 [45. 50. 55. 60.]
 [65. 70. 75. 80.]]


In [13]:
tf.reset_default_graph()
new_filter = np.zeros([7,7,1,1,]).astype(np.float32)
new_filter[0::3,0::3,:,:] = filter_np
filter = tf.Variable(new_filter)
input = tf.Variable(input_np)
output = tf.nn.conv2d(input, filter, [1,1,1,1], 'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)




_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 0. 0. 2. 0. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 5. 0. 0. 6.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 8. 0. 0. 9.]]
_output
 [[277. 122. 135. 243.]
 [ 73.  30.  35.  60.]
 [117.  50.  55.  96.]
 [175.  74.  81. 141.]]


In [15]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.conv2d(input, filter, [1,1,1,1], 'SAME', dilations=[1,3,3,1])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[277. 122. 135. 243.]
 [ 73.  30.  35.  60.]
 [117.  50.  55.  96.]
 [175.  74.  81. 141.]]


## atrous_conv2d_transpose vs conv2d_transpose

In [18]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.atrous_conv2d_transpose(input,filter,[1,4,4,1],1,'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[ 29.  62.  83.  75.]
 [ 99. 192. 237. 198.]
 [207. 372. 417. 330.]
 [263. 446. 485. 365.]]


In [19]:
tf.reset_default_graph()
filter = tf.Variable(filter_np)
input = tf.Variable(input_np)
output = tf.nn.atrous_conv2d_transpose(input,filter,[1,4,4,1],2,'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[ 46.  58.  70.  86.]
 [ 94. 106. 134. 150.]
 [118. 142. 142. 170.]
 [214. 238. 254. 282.]]


In [20]:
tf.reset_default_graph()

newfilter = np.zeros([5,5,1,1]).astype(np.float32)
newfilter[::2,::2,:,:] = filter_np

filter = tf.Variable(filter_np)

input = tf.Variable(input_np)
output = tf.nn.atrous_conv2d_transpose(input,filter,[1,4,4,1],1,'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[ 29.  62.  83.  75.]
 [ 99. 192. 237. 198.]
 [207. 372. 417. 330.]
 [263. 446. 485. 365.]]


In [22]:
tf.reset_default_graph()

newfilter = np.zeros([5,5,1,1]).astype(np.float32)
newfilter[::2,::2,:,:] = filter_np[::-1,::-1,:,:]

filter = tf.Variable(filter_np)

input = tf.Variable(input_np)
output = tf.nn.conv2d(input,filter,[1,1,1,1],'SAME')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _input, _filter, _output = sess.run([input, filter, output])
    _input = np.squeeze(_input)
    _filter = np.squeeze(_filter)
    _output = np.squeeze(_output)

print('_input\n',_input)
print('_filter\n',_filter)
print('_output\n',_output)

_input
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
_filter
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
_output
 [[111. 178. 217. 145.]
 [231. 348. 393. 252.]
 [363. 528. 573. 360.]
 [197. 274. 295. 175.]]
